### ISSUE TITLE
How to unlink entities in many to many relationship?

### ISSUE THREAD

**Issue by mbcrawfo** [simple-odata-client/Simple.OData.Client#441]
As described in #194 when unlinking Simple.OData performs a DELETE call to http://host/entity(id)/navProperty/$ref?$id=navProperty(key).  However the OData v4 spec requires a full url (http://host/navProperty(key)) and and the OData WebApi framework will not route correctly unless a full url is provided.

Am I missing something?  Surely a fundamental operation like updating relationships hasn't been broken for 2+ years.  Is there another way to delete relationships or to make this work?

**Comment by Discjoggy** [comment]
We use aspnetcore and ran into the same issue. Linking entities working well, but unlinking always results in a `System.NullReferenceException` and the reason is: 

`Route value 'null' with key 'ODataConstraint' did not match the constraint 'Microsoft.AspNet.OData.Routing.VersionedODataPathRouteConstraint'`

This issue is one of the newest but it was opened in 2017 :/
