### ISSUE TITLE
QueryOptions not available in some places

### ISSUE THREAD

**Issue by mwchan** [simple-odata-client/Simple.OData.Client#499]
Hi,

This relates to https://github.com/object/Simple.OData.Client/issues/124 and the QueryOptions was added. Can the same option be added when performing functions such as DeleteEntryAsync and UpdateEntryAsync?

Thanks!

**Comment by object** [comment]
Both DeleteEntryAsync and UpdateEntryAsync are applied to the resource looked up by a key, e.g.:

```
            await _client
                .For("Products")
                .Key(product["ID"])
                .DeleteEntryAsync();

```

I am not sure how QueryOptions can be used here since the entry is identified by a key? Can you give an example?

**Comment by mwchan** [comment]
Hi,

Sorry for not providing more information. 

The QueryOptions might contain extra parameters that triggers some business logic that the backend requires to uniquely identify the record as the Key alone might be insufficient. An example would be if the parameter is not enabled, it would use the user's default department. If it is enabled, it might search across all department.

What I had to do was the following:

```
var fluentClient = GetFluentClient()
                .For(collection);

 if (_settings.EnableMyCustomParameter)
 {
                var queryOptions = new Dictionary<string, object> { { "custom-parameter", true } };
                fluentClient.QueryOptions(queryOptions);
 }

var command = fluentClient
                .Key(entryKey)
                .Set(entryData)
                .AsBoundClient().Command;
```

Thanks!

**Comment by object** [comment]
So you would combine both Key and QueryOptions clauses? Can you provide an example of generated UPDATE/DELETE URI that your service would expect?

**Comment by mwchan** [comment]
When I put a breakpoint on the generated command for UPDATE, it is

Customers(Name=%27James%27)?custom-parameter=true

**Comment by object** [comment]
Thanks.

**Comment by mwchan** [comment]
No worries. Please let me know if you need anything else.

**Comment by object** [comment]
Actually it worked for me. Here' the example I tried:


        [Fact]
        public async Task UpdatePersonWithQueryOptions()
        {
            var person = await _client
                .For<Person>()
                .Key("russellwhyte")
                .QueryOptions<QueryOptions>(y => y.IntOption == 42 && y.StringOption == "xyz")
                .Set(new { LastName = "White" })
                .UpdateEntryAsync();
            Assert.Equal("White", person.LastName);
        }

And the generated URI: People(%27russellwhyte%27)?IntOption=42&StringOption='xyz'

Isnt' it correct?

**Comment by object** [comment]
I see, I checked the Fluent API which supports it. I will check the basic API.

**Comment by object** [comment]
I checked basic (non-fluent) API and it looks more complicated than I thought. Methods that assume single entry match take an argument IDictionary<string, object> entryKey. For consistency sake, if I provide queryOptions on basic API, I need to provide an overload for every method that takes entry Key: GetEntryAsync, UpdateEntryAsync, DeleteEntryAsync, LinkEntryAsync, UnlinkEntryAsync. And since they already 2-4 overloads, adding query options variant may double the number of overloads.

Since most of people use fluent API, I thought I could keep basic API reduced.
Why can't you use Update/Delete fluent API with query options?

**Comment by mwchan** [comment]
I implemented this some time ago and had the following documented for DELETE. Can you please read if it makes sense to you? If not I will try writing some code to test it out.

```
//We have to get the list of records back first before deleting them one at a time
//instead of using the oDataQuery.DeleteEntriesAsync which has a limit of '1000' operations
//in a change set. Another limitation of oDataQuery.DeleteEntriesAsync is that internally,
//it is doing a similar thing but it has a limit of reading 10,000 records.
```
For UPDATE, I believe, if you use 

`oDataClient.UpdateEntryAsync(collection, entryKey, entryData)`

it will be more efficient as you are providing it with the entryKey compared to the other method where it would query the record back before sending another request to do an UPDATE.

**Comment by mwchan** [comment]
And I can't do

```
var person = await _client
            .For<Person>()
```

because I do not know the type during compile time. It needs to be a string as it is dynamically obtained during runtime.

**Comment by object** [comment]
Not sure I fully understand you. OData doesn't have API for deleting/updating multiple records at a time, so both DeleteEntriesAsync and UpdateEntriesAsync are just wrappers around single entry Update/Delete that call it in a loop.

And while you don't know the type at a compile time, you can call untyped version of it:
await client.For("CollectionName").etc

You need to know the collection name anyway, can't you? Can't you just use untyped fluent syntax?

**Comment by mwchan** [comment]
Is it correct to say that for DELETE, if I were to call oDataQuery.DeleteEntriesAsync(), the Simple.OData.Client framework, does not support pagination internally? This would mean that it might only delete the first 10,000 records that gets returned?

So what I had to do was to manually get those records back and for each of the record, I had to call oDataClient.DeleteEntryAsync() and pass it the record to delete.

I guess if oDataQuery.DeleteEntriesAsync() supported pagination internally, then I would not need to use oDataClient.DeleteEntryAsync() and thus have no need for QueryOptions to be supported there.

**Comment by mwchan** [comment]
With regards to UPDATE, you are correct that I will be able to use the Fluent API to achieve the same thing but it looks like it doesn't support batch unless I am doing it incorrectly? 

If I need to UPDATE 2 records in a single batch and I call
```
 batch += client => client.UpdateEntryAsync(collection, entryKey, entryData);
```

One single batch request will be sent to the server with
```
POST ....
PATCH..
PATCH..
```

If I need to update 2 records in a single batch and I call
`batch += client => oDataQuery.UpdateEntryAsync();`

4 request non-batch will be sent to the server. There is also an extra GET call involved with every PATCH.
```
Request 1 - PATCH
Request 2 - GET
Request 3 - PATCH
Request 4 - GET
```

**Comment by object** [comment]
@mwchan OData API is different from SQL where you can send a single UPDATE or DELETE statement to the server and will update/delete multiple rows. In OData you have to update/delete single row at a time unless you use BATCH but event in BATCH you need to obtain each record key and specify PATCH or DELETE for each individual records. So I don't think this can be improved using OData protocol. Sometimes I regret that I have exposed UpdateEntries and DeleteEntries methods rather than just having UpdateEntry and DeleteEntry, so people won't get confused into a belief that UpdateEntriesAsync can magically send a single statement to an OData server.

**Comment by mwchan** [comment]
I do understand what you mean and I do not expect it to be in a single statement. The things that I am trying to point out is

1) Batch does not work if you do it this way 
`batch += client => oDataQuery.UpdateEntryAsync();`

2) DeleteEntriesAsync() does not work if the result set is too big as internally it is not doing pagination/annotations.NextPageLink.

Maybe I should create a new issue for each of them instead but I was trying to point out that those are the points that forced me to use the Basic API which did not support QueryOptions.

**Comment by object** [comment]
Adding pagination to Update/DeleteEntries will make it even more confusing. OData supports pagination on safe (read-only) calls, so unless some other process is changing data simultaneously, you can use NextPageLink to continue at a last point. But what will happen if you you NextPageLink while deleting rows? Since you are modifying data, NextPageLink will no longer guarantee that you will continue at a place you stopped, because it refers to an offset from the resource collection as it is now, not as it was when you started the operation.
Actually I am now thinking about marking DeleteEntriesAsync and UpdateEntriesAsync as obsolete so they can be removed in the future version. Exposing such API implies certain expectations from its users - for example, since both these methods look like FindEntriesAsync, they are expected to support both query options and pagination. But unlike other API methods, they are not backed but underlying OData API, they simulate how things might have looked if OData had support for set-based updates and deletes like in SQL. IMHO the API will be cleaner if devs will have first use FindEntriesAsync and they apply Delete/UpdateEntryAsync to each result row, just like the library does today. Then they will be in full control of consequences and will not blame the lib for incorrect pagination.

**Comment by object** [comment]
I see what you mean. Let me think what can be done in a batch scenario.

**Comment by phatcher** [comment]
@object One way around this might be to remove them from the API but implement them as extensions, that way there's a first-cut implementation but a user can write their own if needed.

**Comment by object** [comment]
@mwchan I am trying to figure out semantics of combining a key with custom query options. According to OData documentation, addressing a resource by a key MUST result in a single response (or error if resource is not found). That means that once you obtain a key for an entity to be updated or deleted, it should be sufficient to use this key to update or delete the entity. If providing a key results in multiple entities, this is an implementation error on a server side.
