### ISSUE TITLE
Entity Code generator #Question #Feature

### ISSUE THREAD

**Issue by lobster2012-user** [simple-odata-client/Simple.OData.Client#593]
Hello.
Are there any plans for implementing the t4 class generator?
Should I use something else?

**Comment by object** [comment]
Some time ago I looked into a possibility for creating T4 generator. But it appeared to be more effort than I had time. And since this is not a part of core functionality, I decided to prioritise other things. So the answer is no, there no plans from my side. Of course anyone who wants to take an initiative is welcome :-)

**Comment by lobster2012-user** [comment]
@object 
I understand, I will close the issue.

**Comment by jafin** [comment]
@lobster2012-user  We've used this with success to generate poco classes https://github.com/moh-hassan/odata2poco

**Comment by NetTecture** [comment]
Actaully I would love a decent code generator. As much as the flexibility in SOC is amazing - it also means that intellisense does not work. Being able to actually have a hard generated set of classes with methods to call (even if those again are EntitiySet acutally being For<X> - allows one to easier catch retired functions etc. I acutally am likely going to try to implement something analogue for odata on typescript "nowish" due to - handcoding being a pain.

**Comment by object** [comment]
@NetTecture But did you try OData2Poco that @jafin recommended?

**Comment by NetTecture** [comment]
@object I do not think it makes enough. I want something that generates somehting like a DbContext in EF. Bascially not JUST poco's but a classs hierarchy that represents the complete API (like db first in DbCOntext, basically). Changes then lead to compile errors and not runtime issues. This is much less an "object and properties" issue but one that you rename elements and then dynamic code just does not work ;)

**Comment by phatcher** [comment]
The problem I can see is how to enhance the resulting code without it being lost on regeneration e.g. a lot of my client classes are presented by my MVC controllers so I have to add things like DisplayName and UIHint attributes.

I suppose these could be added via generator conventions and also if we generate them as partial classes additional code can be added via additional files.

I've written code generators using T4 before, but I suppose now you would use Rolsyn

**Comment by NetTecture** [comment]
Generally partial classes. I handcraft API classes in the backend - so basically for C# I just use the api classes anyway - but for a third party I generally keep them "free" or would use partial classes.
