### ISSUE TITLE
Additional DELETE request https://uri/odata/EntitySet(Id)/NavigationProperty/$ref

### ISSUE THREAD

**Issue by MayorSheFF** [simple-odata-client/Simple.OData.Client#757]
Hi Everyone,

Maybe someone has run into this issue.

My app just creates or updates an entity, but I noticed after some PATCH requests my service gets DELETE request which looks like https://uri/odata/EntitySet(Id)/NavigationProperty/$ref . Through whole source code I don't have any deleting operation for this entity (to be honest for other too). Can it happens when NavigationProperty of the Entity is set NULL? How can I turn off this behaviour if it is so?

Please, help.

**Comment by andreso-connecterra** [comment]
@MayorSheFF Did you ever get a reply or manage to fix the problem? Thanks

**Comment by andresodio** [comment]
@MayorSheFF Did you ever get a reply or manage to fix the problem? Thanks

**Comment by MayorSheFF** [comment]
Hi @andresodio,

Sorry that I didn't get in contact with you before now.

Unfortunately, no one has not answered yet. :-(

**Comment by MayorSheFF** [comment]
> @MayorSheFF Did you ever get a reply or manage to fix the problem? Thanks

Hi @andresodio,

Sorry that I didn't get in contact with you before now.

Unfortunately, no one has not answered yet. :-(

**Comment by robertmclaws** [comment]
This is happening because `UpdateEntryAsync` parses through the navigation properties and tries to be helpful by deleting any references that have been nulled out.

[You can see this in action here](https://github.com/simple-odata-client/Simple.OData.Client/blob/master/src/Simple.OData.Client.Core/ODataClient.Async.cs#L1064).

I'm thinking through the best way to solve this problem. Will probably be a Session setting like `IgnoreNullLinksOnUpdate` or something like that, or maybe an overload on the method. We'll see.

Will keep everyone posted.

**Comment by robertmclaws** [comment]
This has been fixed in the next build. When it comes out, you can set `ODataClientSettings.IgnoreNavigationPropertiesOnUpdate = true` and all null properties will be ignored.

I've been testing it on an internal release and it works great. Hopefully sometime in the first week of April.
