### ISSUE TITLE
Problem with tests on forked codebase

### ISSUE THREAD

**Issue by rafek1241** [simple-odata-client/Simple.OData.Client#770]
Hi, recently I forked this repository to make some changes and add extensions for some elements - I couldn't run that successfully because the lack of working tests. Do you know why is it happening? 27 unit tests not working and integration tests were really slow. Without working tests I don't want to change anything because of unstable codebase.

**Comment by watfordgnf** [comment]
I get a few as well:
![image](https://user-images.githubusercontent.com/47254805/100753414-bbef8380-33b7-11eb-962a-ac70282ecf56.png)
Integration tests took ~15 minutes total.

**Comment by object** [comment]
That's weird. Mine are all green. I will double-check.

**Comment by object** [comment]
@rafek1241 Integration tests are slow since they check against an external service, so I only run them occasionally. But I always run all unit tests, and they were green for me last time I checked. I will retest.

**Comment by object** [comment]
I spent some time on trying to find what's wrong with tests. It all looks quite strange. If I target .NET Core 3.1 or .NET 5 in test projects, then some .NET Core-targeted tests fail. Same tests work fine when running them as .NET 4x assemblies. And if I go back from .NET Core 3.1 to .NET Core 2.0, then all .NET Core tests succeed.

It all looks like some timing related failures only triggered by .NET Core and later platforms. It doesn't make sense to re-target tests back to .NET Core 2.0 because the actual library code is not affected. If I get more time I can investigate this more, but as I said before, I no longer actively support this project, so I appreciate initiative from others.

**Comment by maxbruecken** [comment]
.NET Core 3.1 (and later) seems to use caches more aggressively as .NET 4.x while working with dynamic objects. So using of e.g. Expression.Constant(this.Value) leads to reusing of the same dynamic object in subsequent calls even if a new dynamic object is created. I will shortly open a pull request with changes in both classes DynamicODataExpression and DynamicODataEntry that fix the caching of dynamics objects.
